language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - ${HOME}/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  slack:
    secure: BqkFJJxjyx7btfyshWvwXI5sZ2lYHDmw74q/0IDQiczeOtAIBZaQcUTYuXgeYpVjBYcsCSzi4IF7kNVVWP4tsnMTjDF1Xrv332B0CtLNC1b+pMZphzQFJ3owTFCcouXKnaUQSgNLppq4Q1DT6WwQAVd7y7K2kLFMj0DANqiTIUujVu2mruIOOIPu4AquD9YX3mp7s/pDVKPAnoS5a5ljEe+HcNx3voxY+Q4+DhANBwkVQvyYmsYkb/biQ0H3udGWylInPSWY8haqpycZ/eltcjvxhmiZwZnT0vwGKI1jA/VXRVaiCW199swU1rae3MW2JRL1Af0v6ktYNA8JKpmK9W7NCRpqVi6OExnmwkZUCcLZoecDSP/YKU1pBxz91ATpBIRM04NfwUkAM+CzZkvxhSch+dGfWMgVAnlonvS9eH1Jm6uqGbnsyGW0MVrpa/Qf11wDTZBQAnqsqWDJmYm80WE0UTUrnI9FVPw5nLBhOqdad/eP6CtGrw9cAnEJwGItZnBOcFOBMZ3afvrxtHpLC5oUadSGqzm7qIZocA5G9G7yZfixqMsx3somVidBTpCLvOd5EY4Ikc8Gs6NMffo1zkTbUge5zGZj/hxEzirMiU0BwZpk9gZnV79OqH4kd5fpMYUQadwOfEZSVdhOAmk00BkKKpYUV8TYnVbkhF81pZU=
